### ISSUE TITLE
Valid urls marked as invalid

### ISSUE THREAD

**Issue by johnduffell** [structured-data/linter#20]
Hi, when I try to validate using: http://linter.structured-data.org/?url=http:%2F%2Fwww.theguardian.com%2Fsociety%2Fhousing
It says that
```
Linter Messages
property schema:url: Object <http://www.theguardian.com/society/housing> not compatible with rangeIncludes (schema:URL)
```
However that URL looks valid to me, assuming it's not including the less than and greater than in the url.

I'm not sure exactly which URL it's referring to and pasting in one ld+json block at a time doesn't show any problems.

Any suggestions or help you can give would be appreciated!  John

**Comment by gkellogg** [comment]
Use an IRI should be compatible with schema:URL, not just literals. This is one of the uses of schema:URL. I thought the reasoner had a case for this, but it seems that it does not.

**Comment by johnduffell** [comment]
@gkellogg thanks for your quick reply!
