### ISSUE TITLE
503 service unavailable validating URLs

### ISSUE THREAD

**Issue by johnduffell** [structured-data/linter#22]
Hi, we are often getting a 503 service unavailable when fetching validation results.  We are not sure if it's something we are doing wrong or if we should just try again later.  This happens on and off all day.  The responses are taking about 16 seconds to come back.  Below are attached an example request and response, although it happens through the web interface too.  Any assistance would be really great!  Thanks.
```
GET /?url=http:%2F%2Fwww.theguardian.com%2Fuk HTTP/1.1
Host: linter.structured-data.org
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json
CSP: active
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6
Cookie: _gat=1; _ga=GA1.2.1146619526.1432724046
```
response:
```
HTTP/1.1 503 Service Unavailable
Connection: keep-alive
Server: Cowboy
Date: Tue, 02 Jun 2015 13:38:50 GMT
Content-Length: 484
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache, no-store

<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

**Comment by gkellogg** [comment]
I'll try to see what I can figure out going through the logs. If you depend on this as part of a workflow, you might consider cloning it and installing on a local server; it's completely unencumbered open-source.

**Comment by gkellogg** [comment]
Sorry, your request fell off of the logs, and I don't really see any evidence of a crash or bad status; may be a Heroku routing issue. I would suggest running locally to see if you can reproduce the issue; you can attach a log if you find something.

**Comment by johnduffell** [comment]
OK thanks for the info, I will have a go at a local install.  It's only intermittent, so it's clearly a transient problem.  Thanks for looking into it for me.

**Comment by johnduffell** [comment]
Seems to work fine locally so must be a network issue.  I'm considering integrating into our build, but is it possible to use the backend validator without spinning up a web server?  Ideally I would just run a command e.g. ```linter http://www.mysite.com/mypage.html``` and it would output the JSON saying if it was valid or not.

**Comment by gkellogg** [comment]
You can use the linter as a library gem. If you look at the [Parser](https://github.com/structured-data/linter/blob/master/lib/rdf/linter/parser.rb) module, you can use this to parse and reason over your input to get back a list of found issues. You could also use other methods in that module, or from the rdf-reasoner gem.

**Comment by johnduffell** [comment]
@gkellogg In the end I just made our tests download rbenv and linter and then called the parser directly, writing the json to stdout.  Seems to work ok so far, I'll see how the reliability goes!

Not sure if it is worth feeding back anything to here, I suspect there's nothing but plumbing there.  But if you want any of it I'm happy to do a PR here too!
https://github.com/guardian/frontend-sanity-tests/pull/16

**Comment by gkellogg** [comment]
Thanks, don't really see anything there that's generically useful. If you come up with something in the future, please reach out again.
