### ISSUE TITLE
strange with link

### ISSUE THREAD

**Issue by evilebottnawi** [structured-data/linter#24]
![screenshot from 2015-08-14 00 29 24](https://cloud.githubusercontent.com/assets/4567934/9262177/8bce4706-421b-11e5-959c-9fdb3d2e05e1.png)
![screenshot from 2015-08-14 00 28 05](https://cloud.githubusercontent.com/assets/4567934/9262156/68d3df68-421b-11e5-8056-702a45dfe46a.png)
```html
<body itemprop="hasPart" itemscope itemtype="http://schema.org/WebPage">
        <link itemprop="breadcrumb" href="breadcrumb">
...
<div id="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList"><meta itemprop="itemListOrder" content="http://schema.org/ItemListOrderUnordered"><ol class="breadcrumb"><li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a itemprop="item" title="Перейти к insteria." href="http://dev0.cms.dev.itgalaxy.company" data-async="true" class="home"><span itemprop="name">insteria</span></a><meta itemprop="position" content="1"></li>
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a itemprop="item" title="Перейти к рубрике Uncategorized" href="/category/uncategorized/" data-async="true" class="taxonomy category"><span itemprop="name">Uncategorized</span></a><meta itemprop="position" content="2"></li>
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><span itemprop="name">Hello world!</span><meta itemprop="position" content="3"></li>
</ol></div>
...
```
It does not make a tree structure.
But  https://developers.google.com/structured-data/testing-tool/ parsing normal

**Comment by gkellogg** [comment]
The `body` element has both `@itemprop` and `@itemscope` properties, which makes it seem to not be a top-level item, which prevents it from being processed, as it is not actually in the scope of an item. If you remove the `itemprop="hasPart"` from the `body` element, you get the following Turtle:

```turtle
@base <http://example.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

 [
    a schema:BreadcrumbList;
    schema:itemListElement [
      a schema:ListItem;
      schema:item <http://dev0.cms.dev.itgalaxy.company>;
      schema:name "insteria";
      schema:position "1"
    ],  [
      a schema:ListItem;
      schema:item <category/uncategorized/>;
      schema:name "Uncategorized";
      schema:position "2"
    ],  [
      a schema:ListItem;
      schema:name "Hello world!";
      schema:position "3"
    ];
    schema:itemListOrder "http://schema.org/ItemListOrderUnordered"
 ] .

 [
    a schema:WebPage;
    schema:breadcrumb <breadcrumb>
 ] .
```

Note that there is no link between the WebPage and the item list, as it is _not_ connected using an `item prop`. You might try the following HTML, instead:

```html
<body itemscope itemtype="http://schema.org/WebPage">
<div id="breadcrumb" itemprop="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList">
  <meta itemprop="itemListOrder" content="http://schema.org/ItemListOrderUnordered">
  <ol class="breadcrumb">
    <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
      <a itemprop="item" title="Перейти к insteria." href="http://dev0.cms.dev.itgalaxy.company" data-async="true" class="home">
        <span itemprop="name">insteria</span>
      </a>
      <meta itemprop="position" content="1">
    </li>
    <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
      <a itemprop="item" title="Перейти к рубрике Uncategorized" href="/category/uncategorized/" data-async="true" class="taxonomy category">
        <span itemprop="name">Uncategorized</span>
      </a><meta itemprop="position" content="2">
    </li>
    <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
      <span itemprop="name">Hello world!</span>
      <meta itemprop="position" content="3">
    </li>
  </ol>
</div>
</body>
```

Note that Google /SDTT does not necessarily parse Microdata according to the specification, so may accept some input which is not called for by the specification. In this case, perhaps, taking a `link` with an `@href` and resolving it using the `@id` of the `div`. IMO, they should indicate when you're using non-standard input.

**Comment by evilebottnawi** [comment]
@gkellogg 
i can't because breadcrumb in WPHeader

**Comment by evilebottnawi** [comment]
@gkellogg how i can do this code?

**Comment by gkellogg** [comment]
The linter is working properly. You may need to work with an SEO specialist to figure out how to get the markup right on your site.

**Comment by evilebottnawi** [comment]
@gkellogg u think linter not working ok, because not parse as google or google linter not working ok

**Comment by gkellogg** [comment]
The linter is parsing according to the Microdata to RDF specification, and is operating properly. If Google is doing something different with it, it is outside the scope of the specification. So, my opinion is that the linter is operating properly.

In general, if you satisfy the linter, you will also satisfy Google, which is the purpose of the linter after all. Other than the advice I gave about, I can't really guide you on your markup beyond what the tool will tell you.
