### ISSUE TITLE
Linter not parsing non-HTML content-types

### ISSUE THREAD

**Issue by gkellogg** [structured-data/linter#26]
Something broke in detecting and parsing non-HTML types. For example, https://w3c.github.io/rdf-tests/turtle/manifest.ttl should lint properly.

Reported on the Structured Data mailing list.

> It seems that the linter sends quite a lot various acceptable media types in the Accept HTTP header, but unfortunately, when receiving non-HTML based content (i.e. application/n-triples) it fails to provide any results and claims an error occurred. Is there any chance of having that corrected? I believe two solutions are available: remove unnecessery media types and leav only those that are actually supported (quick) or present parsers for other media types.

**Comment by gkellogg** [comment]
Can't duplicate problem.

**Comment by Sohail1088** [comment]
https://webpconvertertips.blogspot.com
Check the structure Data

**Comment by jaygray0919** [comment]
works well
https://klpuiljexh.execute-api.us-east-1.amazonaws.com/Prod/?url=https:%2F%2Fwebpconvertertips.blogspot.com%2F

**Comment by jvandriel** [comment]
The linter does seem to work for a url only containing json-ld (and of that mime-type): http://linter.structured-data.org/?url=https:%2F%2Fjoost.blog%2Fschema%2F
