### ISSUE TITLE
Event v. EducationEvent

### ISSUE THREAD

**Issue by jaygray0919** [structured-data/linter#32]
This structure works (2 events):
`			"performerIn": [
				{
				"@type": "Event",
				"name": "Session 1",
				"offers": {
					"@type": "Offer",
					"category": "advice",
					"price": "0",
					"url": "https://en.wikipedia.org/wiki/Academic_advising"
					},
				"workFeatured": {
					"@type": "CreativeWork",
					"name": "Review syllabus"
					},
				"startDate": "2016-01-23",
				"location": {
					"@type": "Place",
					"name": "Review syllabus in ESH-103",
					"address": "ESH-103"
					}
				},{
				"@type": "Event",
				"name": "Session 2",
				"offers": {
					"@type": "Offer",
					"category": "advice",
					"price": "0",
					"url": "https://en.wikipedia.org/wiki/Academic_advising"
					},
				"workFeatured": {
				"@type": "CreativeWork",
					"name": "Problem set 1"
					},
				"startDate": "2016-02-13",
				"location": {
				"@type": "Place",
					"name": "Problem set 1 in ESH-103",
					"address": "ESH-103"
					}
                                  }]
`

However, this structure fails to load (2 events):

`			"performerIn": [
				{
				"@type": "EducationEvent",
				"name": "Session 1",
				"startDate": "2016-01-23",
				"doorTime": "2016-01-23T09:00:00+07:00",
				"duration": "PT3H00M00S",
				"offers": {
					"@type": "Offer",
					"category": "advice",
					"price": "0",
					"url": "https://en.wikipedia.org/wiki/Academic_advising"
					},
				"workFeatured": {
					"@type": "CreativeWork",
					"name": "Review syllabus",
					"description": "",
					"educationalUse": ["group work"],
					"learningResourceType": ["presentation", "discussion"]
					},
				"location": {
					"@type": "Place",
					"name": "Review syllabus in ESH-103",
					"address": "ESH-103"
					}
				},{
				"@type": "EducationEvent",
				"name": "Session 2",
				"startDate": "2016-02-13",
				"doorTime": "2016-02-13T09:00:00+07:00",
				"duration": "PT3H00M00S",
				"offers": {
					"@type": "Offer",
					"category": "advice",
					"price": "0",
					"url": "https://en.wikipedia.org/wiki/Academic_advising"
					},
				"workFeatured": {
					"@type": "CreativeWork",
					"name": "Problem set 1",
					"description": "",
					"educationalUse": ["group work", "assignment"],
					"learningResourceType": ["presentation", "lab results", "discussion"]
					},
				"location": {
					"@type": "Place",
					"name": "Problem set 1 in ESH-103",
					"address": "ESH-103"
					}
				}]
`

The error messages are:

`validation http://example.org/: Failed to parse input document: loading document failed: The same key is defined more than once: author.performerIn.2.@type
`

and

`validation http://example.org/: FATAL Failed to parse input document: loading document failed: The same key is defined more than once: author.performerIn.2.@type: Called from /app/vendor/bundle/ruby/2.3.0/bundler/gems/json-ld-6b5af3315dcd/lib/json/ld/reader.rb:61 
`

IMHO, `linter` is not evaluating `EducationEvent` in the same (correct) way it evaluates `Event`

Note: the JSON-LD may not be valid syntax; it's extracted from a longer file and closure may be wrong. However, the `EducationEvent` syntax is properly parsed by Google SDTT.

/jg

**Comment by gkellogg** [comment]
I can't find a problem with either snippet running them through the linter as well as other tools; perhaps you copied the wrong bit?

The error messages are complaining that you're using `@type` twice within the same JSON object, so it's not a JSON-LD issue, but a JSON issue. Many JSON parsers will ignore duplicate keys (typically choosing the last one they see). The linter runs in a stricter mode where these are considered errors, as that is the purpose of linting a document.

Feel free to re-open with a snippet that fails when pasted into the linter, and include as much of a full parsing (failing) snippet as you can, so I'm not making too much up.
