### ISSUE TITLE
thumbNail

### ISSUE THREAD

**Issue by jaygray0919** [structured-data/linter#33]
Do not understand this error message:
  `property schema:thumbnailURL: No property definition found`

For example:
  `	"@type": "CreativeWorkSeries",
		"name": "Syllabus",
		"thumbnailURL": "https://profalbrecht.files.wordpress.com/2012/07/easycapture3.jpg",
                 ...
`

It is a property; why does it need a property definition?

/jg

**Comment by gkellogg** [comment]
It is a JSON property, but not one defined in schedule,a.org. I suspect you want schematic:thumbnailUrl (note capitalization). The linter is complaining that your using an property (predicate) not defined in a vocabulary.
