### ISSUE TITLE
MusicRelease is invalid

### ISSUE THREAD

**Issue by carrzkiss** [structured-data/linter#35]
I am learning how to utilize the schema plans on my site.
And one of the ones that I am working on now, is a MusicRelease.
However, when i try to validate a sample, it does not validate.
I even copied your json code into the Google Validator, and it
States that it is not valid.
**The type MusicRelease is not a valid type**.

The validator that I am using is here.
https://www.google.com/webmasters/markup-tester/

Could you please assist me, in finding out why?

Thank You
Wayne Barron

**Comment by carrzkiss** [comment]
Never mind. Using that tool is not the best thing to use.
It is best to use: https://developers.google.com/structured-data/testing-tool/

**Comment by gkellogg** [comment]
The linter contains most of the schema.org examples, but seems to be missing MusicRelease at present. I note running the examples from http://schema.org/MusicRelease that the first one has a JSON syntax error, but the second seems to validate properly on the Linter. The schema.org examples used in the Linter  from from the schema.org project on GitHub, but they often let things through that have markup errors.
