### ISSUE TITLE
Request to update LINT BY DIRECT INPUT: linter.structured-data.org

### ISSUE THREAD

**Issue by jeannieh** [structured-data/linter#36]
[On my Hill Web Creations site] (https://www.hillwebcreations.com/) Google's SDTT still can't handle multi-type entities, therefore, I tested several pages using the http://linter.structured-data.org/ tool, pages that the GSC confirms are rich and correct with structured data markup.

WHEN USING LINT URL

"The results returned by the tool are: "Disclaimer: this preview is only shown as a example of what a search engine might display. It is to the discretion of each search engine provider to decide whether your page will be displayed as an enhanced search result or not in their search results pages." 

And then:
"No structured data detected."

WHEN USING LINT BY DIRECT INPUT

Then, I see the results that I expected.

The same issue happens for site [LinkedIn for Business](https://linkedinforbusiness.net).

**Comment by gkellogg** [comment]
Note the lint messages:

```
validation https://www.hillwebcreations.com/: Failed to parse input document: loading document failed: The same key is defined more than once: headline

validation https://www.hillwebcreations.com/: ERROR <https://www.hillwebcreations.com/>: Unexpected end tag : span Unexpected end tag : p

validation https://www.hillwebcreations.com/: FATAL Failed to parse input document: loading document failed: The same key is defined more than once: headline: Called from /app/vendor/bundle/ruby/2.3.0/bundler/gems/json-ld-6b5af3315dcd/lib/json/ld/reader.rb:61

property schema:height: Object "56"^^<http://www.w3.org/2001/XMLSchema#integer> not compatible with rangeIncludes (schema:Distance,schema:QuantitativeValue)

property schema:height: Object "600"^^<http://www.w3.org/2001/XMLSchema#integer> not compatible with rangeIncludes (schema:Distance,schema:QuantitativeValue)

property schema:width: Object "415"^^<http://www.w3.org/2001/XMLSchema#integer> not compatible with rangeIncludes (schema:Distance,schema:QuantitativeValue)

property schema:width: Object "1200"^^<http://www.w3.org/2001/XMLSchema#integer> not compatible with rangeIncludes (schema:Distance,schema:QuantitativeValue)

property schema:query-input: No property definition found

property og:url: Object "https://www.hillwebcreations.com/"@en-us not compatible with range (ogc:url)

property og:image: Object "https://www.hillwebcreations.com/wp-content/uploads/2015/04/custom-internet-marketing-consultation.jpg"@en-us not compatible with range (ogc:url)

property og:image: Object "https://www.hillwebcreations.com/wp-content/uploads/2016/01/minneapolis-digital-marketing-trends-150x140.jpg"@en-us not compatible with range (ogc:url)

property og:image: Object "https://www.hillwebcreations.com/wp-content/uploads/2014/05/hill-web-creations-Jeannie-Hill.jpeg"@en-us not compatible with range (ogc:url)

property og:image: Object "https://www.hillwebcreations.com/wp-content/uploads/2014/05/adwords-ppc-management-350-x320-1.jpg"@en-us not compatible with range (ogc:url)

property og:image: Object "https://www.hillwebcreations.com/wp-content/uploads/2016/01/hill-web-marketing-minneapolis-mn-415x56.jpg"@en-us not compatible with range (ogc:url)

property schema:datePublished: Object "2015-12-01T38:00:00+07:00" not compatible with rangeIncludes (schema:Date)

error NoMethodError: undefined method `strftime' for nil:NilClass
```

There seem to be markup errors, and other things which prevent the site from being accessed properly. You might also try parsing at http://rdf.greggkellogg.net/distiller. You may need to validate your HTML and fix reported errors first.

**Comment by Preedublin** [comment]
I have a similar problem with my webpage [https://dublingasworks.com/gas-boiler-replacement-dublin/](url)
linter.structured is showing "property schema:width: Object "1117"^^<http://www.w3.org/2001/XMLSchema#integer> not compatible with rangeIncludes (schema:Distance,schema:QuantitativeValue)"
How can I fix this?
any idea?

**Comment by jvandriel** [comment]
The issue isn't with the Linter but with the values you provided. Both schema.org/width and schema.org/height expect either a `Distance` or a `QuantitativeValue` or (per schema.org default) a `Text` value, whereas you provided a number values.

So the easiest way to fix this is to provide a string by using double quotes for your values as such:
`"width": "1117"` as opposed to `"width": 1117`.

Otherwise you can also add a `QuantitativeValue` as such:
```
"width": {
  "value": 1117
  "unitText": "pixel",
  "unitCode": "E37"
}
```
