### ISSUE TITLE
IOError: Failed to open ... Errors found during processing

### ISSUE THREAD

**Issue by gerrymi** [structured-data/linter#39]
Hi, I love your structured data linter, it's been a really good tool for learning about structured data. 

I tried creating my own instance your tool using the source you've uploaded here https://github.com/structured-data/linter/releases/tag/2.3.7 but some sites throw this error on my instance while it works perfectly fine on http://linter.structured-data.org/

`error IOError: Failed to open http://www.modelmayhem.com/: Errors found during processing`

`   
ERROR <http://www.modelmayhem.com/>: error parsing attribute name
attributes construct error
Couldn't find end of Start Tag n.length line 5
xmlParseEntityRef: no name
StartTag: invalid element name
Couldn't find end of Start Tag o line 5
EntityRef: expecting ';'
Couldn't find end of Start Tag u line 5
Entity 'v.prototype' not defined
AttValue: " or ' expected
Couldn't find end of Start Tag script line 97
Opening and ending tag mismatch: head line 3 and script
Opening and ending tag mismatch: html line 2 and head
Extra content at the end of the document
`

**Comment by gkellogg** [comment]
What your seeing is errors reported from the HTML parse of the page; they're usually split into multiple lines, but when it comes to the linter output, they're joined together. Try running your site through the [HTML Validator](https://validator.w3.org/check?uri=http%3A%2F%2Fwww.modelmayhem.com&charset=%28detect+automatically%29&doctype=Inline&group=0).

Note that when locally, in development mode, errors are often handled differently. To simulate production mode, try running as follows:

    RACK_ENV=production foreman start
