### ISSUE TITLE
@en not compatible with range (ogc:url) messages for image:secure_url, og:url and og:image

### ISSUE THREAD

**Issue by webcoder-eu** [structured-data/linter#49]
Hi,

Why am I getting these "property... @en not compatible with range (ogc:url)" messages when testing my domain?

Domain: https://webcoder.eu

http://linter.structured-data.org/?url=https:%2F%2Fwebcoder.eu

image:secure_url, og:url and og:image are allowed hence am puzzled.

Thanks,
David
![Screenshot_2019-11-22 Structured Data Linter](https://user-images.githubusercontent.com/4722892/69459928-c6217f80-0d6a-11ea-9275-6ee9a672301a.png)

**Comment by gkellogg** [comment]
Without looking at your page source, I suspect that you are setting a Lang attribute (or `@language` in JSON-LD) and the property value is being interpreted as a text string, rather than a URI. If using JSON-LD, either don’t set `@language`, at least for that property, or better yet, use the expanded value form `{“@id”: “https://...”}`. If using Microdata or RDFa, use an href attribute.

**Comment by gkellogg** [comment]
But, the linter/reasoner, could probably figure out to ignore the language in this case.

**Comment by webcoder-eu** [comment]
Correct, when remove ' lang="en" ' from <html lang="en"> it's not complaining anymore. Am doing reseach on whether removing is a good thing for google.

Many thanks

**Comment by webcoder-eu** [comment]
hmm... not html is not validating nicely as before so will rather ignore linter/reasoner and live with its messages.

<img width="1016" alt="Screenshot 2019-11-22 at 21 30 58" src="https://user-images.githubusercontent.com/4722892/69461912-9163f700-0d6f-11ea-986b-0c1a6f4af37b.png">

**Comment by gkellogg** [comment]
This looks like the line that's causing the problem:

```html
<meta property="og:image:secure_url" content="https://webcoder.eu/assets/img/logosocial.jpg">
```

The problem is that meta interprets context as text, you could consider using a link element:

```html
<link property="og:image:secure_url" href="https://webcoder.eu/assets/img/logosocial.jpg">
```

That interprets the value as a URL and should avoid the problem (and is really the right thing to do).

Of course, given that it's an image, you could also use an img element.

**Comment by webcoder-eu** [comment]
Changed it link and href as above but unfortunately it's still complaining. At least HTML is validatinng now.

> Linter Messages
> 
> class ogc:url: No class definition found
> 
> property og:url: Object "https://webcoder.eu/"@en not compatible with range (ogc:url)
> 
> property og:image: Object "https://webcoder.eu/assets/img/logosocial.jpg"@en not compatible with range (ogc:url) 


![Screenshot_2019-11-22 Structured Data Linter(1)](https://user-images.githubusercontent.com/4722892/69464930-ab093c80-0d77-11ea-9ee9-8cc4053ec8c7.png)

**Comment by webcoder-eu** [comment]
I don't quite understand why a valid HTML lang is affecting it

**Comment by webcoder-eu** [comment]
Only one message left after changing all tags containing urls to <link... href=

Linter Messages
class ogc:url: No class definition found 

![Screenshot_2019-11-22 Structured Data Linter(2)](https://user-images.githubusercontent.com/4722892/69465358-e22c1d80-0d78-11ea-9574-74f6cc28a588.png)

![Screenshot 2019-11-22 at 22 38 57](https://user-images.githubusercontent.com/4722892/69465371-eb1cef00-0d78-11ea-8768-aa051b193373.png)

**Comment by webcoder-eu** [comment]
but now my og appears to be broken

![Screenshot 2019-11-22 at 22 41 11](https://user-images.githubusercontent.com/4722892/69465514-464ee180-0d79-11ea-98bd-1dd1abf72329.png)

**Comment by gkellogg** [comment]
I can’t really debug your markup for you, but the messages seem reasonable. Of course, it’s only advisory, and you may ignore it. 

The linter uses semantic reasoning to make these determinations, based on the definitions of the vocabulary terms you use.

**Comment by tacsup** [comment]
In my website also similar issue facing 
Home page 
error RDF::ReaderError: Statement #<RDF::Statement:0x7a0f8(nil nil nil .)> is incomplete on linter

my web url : https://www.tacsllc.com/ please help

**Comment by marcoscazaux** [comment]
The correct solution is add the "prefix" property to html tag.
`<html prefix="og: https://ogp.me/ns#">`

**Comment by Tachi107** [comment]
@marcoscazaux but why is it needed? RDFa 1.1 has `og` in its predefined vocabulary prefixes: <https://www.w3.org/2011/rdfa-context/rdfa-1.1#crawl>
