### ISSUE TITLE
Bug when linting JSON-LD with aggregateRating

### ISSUE THREAD

**Issue by rafaelgomesxyz** [structured-data/linter#67]
When linting JSON-LD with `aggregateRating`, an error happens:

`
error RDF::ReaderError: wrong number of arguments (given 0, expected 1)
`

This error happens even with the examples provided here: http://linter.structured-data.org/examples/schema.org/AggregateRating/

**Comment by gkellogg** [comment]
Deployed in 3.14.1.

**Comment by rafaelgomesxyz** [comment]
Tested locally and it works now, thanks for the quick fix!

**Comment by gkellogg** [comment]
Heroku issued some security updates, and it's not connecting to the repo any longer, so still need to work on deploying live.

**Comment by gkellogg** [comment]
Okay, deployed now.
